Repository loggi/django-graphql-db-router, pull requests merged in 2019-10, with the labels that each got.

#2 chore(git): add gitignore file
  .gitignore
Labels: enhancement

#4 chore(django): add requirements
  requirements.txt
Labels: enhancement

#5 chore(travis): add travis simple configuration file
  .travis.yml
Labels: enhancement

#7 fix(django): adjust version due a vulnerability detected
  requirements.txt
Labels: bug

#8 Chore/flake8
  .travis.yml
  requirements.txt
Labels: enhancement

#10 chore: add .idea/ directory to .gitignore
  .gitignore
Labels: ready for review

#11 feat: create decorator and context manager for reading from RO db
  db/router.py
Labels: ready for review

#13 chore: add pipenv files
  requirements/Pipfile
  requirements/Pipfile.lock
Labels: ready for review

#12 chore: create Python package setup file
  setup.py
Labels: ready for review
